### PR TITLE
fix(ApiAppActionCategories):  export the actual type [EXT-3618]

### PR DESCRIPTION
**Pull request by kdamball**
## Summary

forgot to expose the new type in #1328  🤦🏾 

## Checklist (check all before merging)

- [ ] Both unit and integration tests are passing
- [ ] There are no breaking changes
- [ ] Changes are reflected in the documentation

When adding a new method:

- [ ] The new method is exported through the default and plain CMA client
- [ ] All new public types are exported from `./lib/export-types.ts`
- [ ] Added a unit test for the new method
- [ ] Added an integration test for the new method
- [ ] The new method is added to the documentation

### CODE REVIEW

**Review by shikaan — APPROVED** [review]

**Comment by andipaetzold** [comment]
The naming `Api....` is not really consistent with all other exported entity types. Can't we call this `AppActionCategory`? Yes, that's the name of the enum, but I think we should try to stay consistent

**Comment by andipaetzold** [comment]
🤦  It should be `AppActionCategoryProps` for consistency. I messed up myself in the comment.

**Comment by kdamball** [comment]
@andipaetzold considering it contains `sys`, I wouldn't call this props but rather the entity name itself.

**Review by Spring3 — APPROVED** [review]

**Comment by andipaetzold** [comment]
@kdamball In CMA.js the `...Props` interfaces always represent the entity as a plain object wthout any methods. The "non-props" interfaces always include methods like `toPlainObject` or similar and are used for the nested CMA client

E.g. AppDefinition:
* [AppDefinitionProps](https://github.com/contentful/contentful-management.js/blob/18b12c912b412ad89db1c77cb9bec0bf3116002c/lib/entities/app-definition.ts#L40-L70)
* [`AppDefinition` and method creating `AppDefinition`](https://github.com/contentful/contentful-management.js/blob/18b12c912b412ad89db1c77cb9bec0bf3116002c/lib/entities/app-definition.ts#L77-L97)

**Pull request merged**
