### PR TITLE
feat(space_memberships): Pass query parameters

### PR DESCRIPTION
**Pull request by msalpietro**
Pass query params for pagination, skip and limit

### CODE REVIEW

**Comment by axe312ger** [comment]
Thank you for your contribution @msalpietro 

Two minor things:

1. Could you please remove the changes you did to `lib/create-contentful-api.js` from the PR? I agree thats trailing white space but it should not be part of this PR
2. You missed the jsdocs comment for the function which is used to generate the documentation of this library. You might steal it from other collection endpoint functions:

```
* @param  {Object=} query - Object with search parameters. Check the <a href="https://www.contentful.com/developers/docs/javascript/tutorials/using-js-cda-sdk/#retrieving-entries-with-search-parameters">JS SDK tutorial</a> and the <a href="https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters">REST API reference</a> for more details.
```

All the best,
Benedikt

**Comment by msalpietro** [comment]
Fixed.

**Comment by axe312ger** [comment]
@msalpietro You are still missing the query parameter docs 🙈 

You may just add
```
* @param  {Object=} query - Object with search parameters. Check the <a href="https://www.contentful.com/developers/docs/javascript/tutorials/using-js-cda-sdk/#retrieving-entries-with-search-parameters">JS SDK tutorial</a> and the <a href="https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters">REST API reference</a> for more details.
```
to line 831

Thanks! :)

**Comment by msalpietro** [comment]
Oops, added in the example but forgot the param line. Added.

**Pull request merged**
