### PR TITLE
feat: add delivery function entity and types [MONET-1417]

### PR DESCRIPTION
**Pull request by pciazynski**
## Summary
Contentful will soon support a new entity called DeliveryFunction. This PR adds typings for this entity.

### CODE REVIEW

**Review by cemreyuksel — APPROVED** [review]
LGTM 🎉 

Is `allowNetworks` a required parameter?

**Comment by pciazynski** [comment]
> LGTM 🎉
> 
> Is `allowNetworks` a required parameter?

Not sure tbh, @kdamball what do you think about it?

**Comment by kdamball** [comment]
> Is allowNetworks a required parameter?

It's optional but we can also send an empty array

**Review by andreascful — APPROVED** [review]

**Comment by pciazynski** [comment]
OK, I made it optional

**Pull request merged**
