### PR TITLE
feat: rename getAll to getMany for tasks and comments

### PR DESCRIPTION
**Pull request by Chaoste**
## Summary

- Add task.getManyForEntry
- feat: rename to getManyForEntry for consistency and allow passing pagination parameters

BREAKING CHANGE: Rename `getAll` to `getManyForEntry` for tasks and comments in plain client.

## Description

Due to pipeline issues in https://github.com/contentful/contentful-management.js/pull/1262 and some missing fixes & improvements I cherry picked the commit by @dmsolutionsmn (for keeping authorship) and added the refactoring & fix.

## Checklist (check all before merging)

- [x] Both unit and integration tests are passing
- [x] There are no breaking changes
- [x] Changes are reflected in the documentation

When adding a new method:

- [x] The new method is exported through the default and plain CMA client
- [x] All new public types are exported from `./lib/export-types.ts`
- [x] Added a unit test for the new method
- [x] Added an integration test for the new method
- [x] The new method is added to the documentation

### CODE REVIEW

**Review by giotiskl — APPROVED** [review]

**Review by andipaetzold — CHANGES_REQUESTED** [review]
Changing the name of the action from `getAll` to `getManyForEntry` is a breaking change and would break all existing apps using that method via the cma adapter

**Comment by marcolink** [comment]
I suggest adding a deprecation warning for `getAll` and introducing `getManyForEntry` additionally for the reasons @andipaetzold mentioned.

**Comment by marcolink** [comment]
Sorry, I might have not read things carefully enough.

**Comment by Chaoste** [comment]
Mmmh, so do we roll out changes to methods in CMA only with new major versions? Totally makes sense to me but I wasn't aware of it so far 😅 
This thing is not urgent because it's only about the clean-up in CMA, it doesn't really add functionality. So how about this is on hold until the next major version? That being said, is there a release plan?

**Review by andipaetzold — APPROVED** [review]

**Pull request merged**
