### PR TITLE
chore: convert ui-extension to typescript

### PR DESCRIPTION
**Pull request by suevalov**
Converts `entities/ui-extension` to Typescript

### CODE REVIEW

**Comment by marcolink** [comment]
@suevalov 
Great work!
But isn't this meant to be based on `experimental` branch? or i this part meant to go into the next release?

**Comment by suevalov** [comment]
@marcolink nope, this typescript refactoring is not related to an experimental branch and should go to master. The sooner we convert master to TS - the better for an experimental branch.

**Pull request merged**
